services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: /api
    container_name: youthpreneur-frontend
    restart: unless-stopped
    ports:
      - '80:80'
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: backend-image:latest # Ganti dengan image backend Anda
    container_name: backend
    restart: unless-stopped
    expose:
      - '8080'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
