export default {
  semi: true,
  singleQuote: true,
  trailingComma: 'es5',
  tabWidth: 2,
  useTabs: false,
  printWidth: 100,
  bracketSpacing: true,
  bracketSameLine: false,
  arrowParens: 'always',
  endOfLine: 'lf',
  quoteProps: 'as-needed',
  jsxSingleQuote: false,
  proseWrap: 'preserve',
  htmlWhitespaceSensitivity: 'css',
  embeddedLanguageFormatting: 'auto',
  plugins: ['@trivago/prettier-plugin-sort-imports', 'prettier-plugin-tailwindcss'],
  importOrder: [
    '^(react/(.*)$)|^(react$)',
    '<SEPARATOR>',
    '<THIRD_PARTY_MODULES>',
    '<SEPARATOR>',
    '^@/config/(.*)$',
    '<SEPARATOR>',
    '^@/lib/(.*)$',
    '<SEPARATOR>',
    '^@/layouts/(.*)$',
    '<SEPARATOR>',
    '^@/components/(.*)$',
    '<SEPARATOR>',
    '^@/hooks/(.*)$',
    '<SEPARATOR>',
    '^@/types/(.*)$',
    '<SEPARATOR>',
    '^@/constants/(.*)$',
    '<SEPARATOR>',
    '^lucide-react$',
    '<SEPARATOR>',
    '^[./]',
  ],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
  importOrderParserPlugins: ['typescript', 'jsx'],
  tailwindFunctions: ['clsx', 'cn', 'cva'],
};
