import type {
  CategoryOption,
  KecamatanInfo,
  SectorStat,
  StatusOption,
  YouthCategory,
  YouthProfile,
} from '@/types/database';

export const YOUTH_DATABASE: YouthProfile[] = [
  {
    id: 'TPN-001',
    nama: 'Siti Rahmah',
    usaha: 'Sambal Hiyung Barokah',
    kecamatan: 'Tapin Selatan',
    kategori: 'Kewirausahaan',
    status: 'Memiliki NIB',
    badgeColor: 'bg-brand-yellow',
    icon: '🌶️',
    produk: 'Olahan Cabai Hiyung Kemasan Botol',
    deskripsi:
      'Mengolah cabai rawit Hiyung khas Tapin Selatan menjadi sambal siap saji berbagai varian. Telah bersertifikasi NIB dan P-IRT, memasok ke supermarket di Rantau & Banjarmasin.',
    kontak: '0812-5544-1234',
  },
  {
    id: 'TPN-002',
    nama: 'Muhammad Zaini',
    usaha: 'Purun Art Bakarangan',
    kecamatan: 'Bakarangan',
    kategori: 'Kriya & Kreatif',
    status: 'Binaan Aktif',
    badgeColor: 'bg-brand-purple',
    icon: '🧺',
    produk: 'Anyaman Tas Purun Etnik & Ecoprint',
    deskripsi:
      'Generasi muda pelestari anyaman purun rawa di Bakarangan. Menghasilkan tas fesyen modern kombinasi ecoprint daun jati yang dipasarkan di pameran nasional.',
    kontak: '0852-8921-8765',
  },
  {
    id: 'TPN-003',
    nama: 'Rizky Pratama',
    usaha: 'Balipat Racing Team Tapin',
    kecamatan: 'Binuang',
    kategori: 'Olahraga & Prestasi',
    status: 'Juara Daerah',
    badgeColor: 'bg-brand-mint',
    icon: '🏍️',
    produk: 'Pebalap Road Race & Perbengkelan',
    deskripsi:
      'Atlet balap motor binaan sirkuit Balipat Binuang peraih medali perak Kejurda Kalimantan Selatan. Mengelola sekolah mekanik muda untuk pemuda Binuang.',
    kontak: '0821-9988-3456',
  },
  {
    id: 'TPN-004',
    nama: 'Nabila Ananda',
    usaha: 'Sasirangan Pewarna Alami Ruhui',
    kecamatan: 'Tapin Utara',
    kategori: 'Kriya & Kreatif',
    status: 'Binaan Aktif',
    badgeColor: 'bg-brand-purple',
    icon: '🎨',
    produk: 'Kain Sasirangan Ramah Lingkungan',
    deskripsi:
      'Inovator muda kain sasirangan menggunakan pewarna alami limbah kulit jering dan kayu ulin khas Tapin. Aktif mengisi galeri cinderamata Kabupaten Tapin.',
    kontak: '0813-7766-5544',
  },
  {
    id: 'TPN-005',
    nama: 'Ahmad Baihaki',
    usaha: 'Madu Kelulut Meratus Piani',
    kecamatan: 'Piani',
    kategori: 'Kewirausahaan',
    status: 'Memiliki NIB',
    badgeColor: 'bg-brand-yellow',
    icon: '🍯',
    produk: 'Madu Trigona Murni Pegunungan',
    deskripsi:
      'Membudidayakan lebah madu tanpa sengat (kelulut) di kawasan lereng Pegunungan Meratus dekat Bendungan Tapin. Menggerakkan pemuda adat Dayak Meratus.',
    kontak: '0878-1122-3344',
  },
  {
    id: 'TPN-006',
    nama: 'Fajar Rahman',
    usaha: 'Ruhui Creative Studio',
    kecamatan: 'Lokpaikat',
    kategori: 'Teknologi & Digital',
    status: 'Binaan Aktif',
    badgeColor: 'bg-brand-blue',
    icon: '💻',
    produk: 'Jasa Branding, Desain & Social Media',
    deskripsi:
      'Agensi kreatif pemuda yang membantu lebih dari 40 UMKM lokal Tapin memotret produk, membuat logo kemasan, dan mengelola kampanye iklan di TikTok Shop.',
    kontak: '0857-4433-2211',
  },
  {
    id: 'TPN-007',
    nama: 'Gusti Ayu Maulida',
    usaha: 'Ikan Sepat Rawa Barokah',
    kecamatan: 'Candi Laras Utara',
    kategori: 'Kewirausahaan',
    status: 'Memiliki NIB',
    badgeColor: 'bg-brand-yellow',
    icon: '🐟',
    produk: 'Ikan Asin Kering Higienis & Kerupuk',
    deskripsi:
      'Memanfaatkan limpahan ikan air rawa tawar di Margasari dengan teknologi solar dryer pengeringan higienis. Produk dikemas dalam pouch modern kedap udara.',
    kontak: '0822-6677-8899',
  },
  {
    id: 'TPN-008',
    nama: 'Rendy Saputra',
    usaha: 'Tapin Smart Farming Hub',
    kecamatan: 'Tapin Tengah',
    kategori: 'Kewirausahaan',
    status: 'Binaan Aktif',
    badgeColor: 'bg-brand-yellow',
    icon: '🌾',
    produk: 'Bibit Unggul & Pupuk Organik Cair',
    deskripsi:
      'Pelopor pertanian presisi generasi muda di Tapin Tengah, menyediakan bibit unggul cabai dan formulasi pupuk organik cair ramah lingkungan.',
    kontak: '0812-3344-9988',
  },
  {
    id: 'TPN-009',
    nama: 'Noor Latifah',
    usaha: 'Kopi Haruyan Meratus',
    kecamatan: 'Hatungun',
    kategori: 'Kewirausahaan',
    status: 'Memiliki NIB',
    badgeColor: 'bg-brand-yellow',
    icon: '☕',
    produk: 'Biji Kopi Robusta Roasting Khusus',
    deskripsi:
      'Menghidupkan kembali kebun kopi dataran tinggi Hatungun. Menjual kemasan drip bag coffee khas Tapin untuk oleh-oleh wisatawan.',
    kontak: '0853-2211-7788',
  },
  {
    id: 'TPN-010',
    nama: 'Dedi Irawan',
    usaha: 'Panahan Tradisional Tapin',
    kecamatan: 'Salam Babaris',
    kategori: 'Olahraga & Prestasi',
    status: 'Juara Daerah',
    badgeColor: 'bg-brand-mint',
    icon: '🏹',
    produk: 'Klub Panahan Tradisional & Pembuat Busur',
    deskripsi:
      'Atlet panahan peraih medali emas Kejurda Kalsel sekaligus perajin busur panah tradisional dari kayu lokal berkualitas tinggi.',
    kontak: '0896-5544-1122',
  },
  {
    id: 'TPN-011',
    nama: 'Maulida Hasanah',
    usaha: 'Wadah Wadai Banjar Rantau',
    kecamatan: 'Tapin Utara',
    kategori: 'Kewirausahaan',
    status: 'Binaan Aktif',
    badgeColor: 'bg-brand-yellow',
    icon: '🧁',
    produk: 'Bingka & Amparan Tatak Kemasan Vakum',
    deskripsi:
      'Modernisasi kue basah tradisional khas Banjar dengan metode sterilisasi vakum sehingga tahan kirim ke luar pulau tanpa bahan pengawet.',
    kontak: '0811-9988-7766',
  },
  {
    id: 'TPN-012',
    nama: 'Wahyu Ramadhan',
    usaha: 'Kelompok Sadar Wisata Rawa Candi',
    kecamatan: 'Candi Laras Selatan',
    kategori: 'Sosial & Komunitas',
    status: 'Binaan Aktif',
    badgeColor: 'bg-brand-peach',
    icon: '🛶',
    produk: 'Paket Wisata Perahu Danau & Bird Watching',
    deskripsi:
      'Inisiatif pemuda desa mengelola wisata susur rawa lebak dan konservasi burung endemik air di Candi Laras Selatan.',
    kontak: '0812-4455-6677',
  },
];

export const CATEGORY_OPTIONS: CategoryOption[] = [
  { value: 'ALL', label: 'Semua Kategori', hover: 'hover:bg-brand-yellow' },
  { value: 'Kewirausahaan', label: '🌱 Wirausaha & Agribisnis', hover: 'hover:bg-brand-yellow' },
  { value: 'Kriya & Kreatif', label: '🎨 Kriya & Kreativitas', hover: 'hover:bg-brand-purple' },
  {
    value: 'Teknologi & Digital',
    label: '💻 Digital & IPTEK',
    hover: 'hover:bg-brand-blue',
  },
  {
    value: 'Olahraga & Prestasi',
    label: '🏅 Olahraga & Prestasi',
    hover: 'hover:bg-brand-mint',
  },
  { value: 'Sosial & Komunitas', label: '🤝 Komunitas & Pemuda', hover: 'hover:bg-brand-peach' },
];

export const STATUS_OPTIONS: StatusOption[] = [
  { value: 'ALL', label: 'Semua Status' },
  { value: 'Binaan Aktif', label: 'Binaan Aktif Dispora' },
  { value: 'Memiliki NIB', label: 'Legalitas NIB Lengkap' },
  { value: 'Juara Daerah', label: 'Peraih Prestasi' },
];

export const KECAMATAN_FILTER_OPTIONS = [
  'Tapin Utara',
  'Tapin Tengah',
  'Tapin Selatan',
  'Bakarangan',
  'Binuang',
  'Hatungun',
  'Lokpaikat',
  'Piani',
  'Salam Babaris',
  'Candi Laras Utara',
  'Candi Laras Selatan',
] as const;

export const KECAMATAN_INFO: KecamatanInfo[] = [
  {
    name: 'Tapin Utara',
    focus: 'Ibukota Rantau & Industri Kreatif',
    description: 'Kuliner modern, sasirangan etnik, agensi digital, & pusat olahraga.',
    count: '240+',
    dot: 'bg-amber-400',
    accent: 'text-amber-800',
  },
  {
    name: 'Tapin Selatan',
    focus: 'Sentra Cabai Hiyung Nasional',
    description: 'Cabai terpedas Indonesia, hilirisasi abon cabai, dan agrowisata.',
    count: '195+',
    dot: 'bg-red-400',
    accent: 'text-red-700',
  },
  {
    name: 'Tapin Tengah',
    focus: 'Pertanian Padi & Hortikultura',
    description: 'Smart farming pemuda, pembibitan cabai, dan lumbung pangan lokal.',
    count: '130+',
    dot: 'bg-emerald-400',
    accent: 'text-emerald-800',
  },
  {
    name: 'Bakarangan',
    focus: 'Pusat Kerajinan Anyaman Purun',
    description: 'Kriya purun ekspor, tas anyaman etnik, & inovasi ecoprint.',
    count: '142+',
    dot: 'bg-purple-400',
    accent: 'text-purple-800',
  },
  {
    name: 'Binuang',
    focus: 'Sport Tourism & Otomotif',
    description: 'Sirkuit Balipat, atlet balap motor, perbengkelan modern & ritel.',
    count: '210+',
    dot: 'bg-blue-400',
    accent: 'text-blue-800',
  },
  {
    name: 'Hatungun',
    focus: 'Perkebunan Karet & Agroforestri',
    description: 'Kopi lereng bukit, madu trigona, dan kelompok tani muda.',
    count: '98+',
    dot: 'bg-amber-600',
    accent: 'text-amber-900',
  },
  {
    name: 'Lokpaikat',
    focus: 'Sentra UMKM Pangan & Logistik',
    description: 'Olahan makanan ringan, keripik, packaging hub, & kepemudaan.',
    count: '115+',
    dot: 'bg-sky-400',
    accent: 'text-sky-800',
  },
  {
    name: 'Piani',
    focus: 'Bendungan Tapin & Ekowisata',
    description: 'Madu kelulut Meratus, pemandu wisata alam, budaya Dayak Meratus.',
    count: '86+',
    dot: 'bg-emerald-600',
    accent: 'text-emerald-900',
  },
  {
    name: 'Salam Babaris',
    focus: 'Agrobisnis Kelapa Sawit & Ternak',
    description: 'Peternakan kambing/sapi terpadu dan koperasi pemuda mandiri.',
    count: '104+',
    dot: 'bg-yellow-500',
    accent: 'text-yellow-900',
  },
  {
    name: 'Candi Laras Utara',
    focus: 'Perikanan Rawa & Semangka',
    description: 'Ikan asin sepat/haruan, semangka rawa lebak, dan transportasi air.',
    count: '78+',
    dot: 'bg-teal-400',
    accent: 'text-teal-800',
  },
  {
    name: 'Candi Laras Selatan',
    focus: 'Budidaya Ikan & Wisata Air',
    description: 'Keramba apung, pengolahan kerupuk ikan haruan, & susur sungai.',
    count: '82+',
    dot: 'bg-cyan-400',
    accent: 'text-cyan-800',
  },
];

export const SECTOR_STATS: SectorStat[] = [
  {
    label: 'Kuliner (Makanan & Minuman)',
    value: 24,
    detail: '356 Data',
    bar: 'bg-amber-400',
  },
  {
    label: 'Fashion, Kriya & Kerajinan',
    value: 18,
    detail: '267 Data',
    bar: 'bg-purple-300',
  },
  {
    label: 'Perdagangan, Ritel & Sembako',
    value: 17,
    detail: '252 Data',
    bar: 'bg-rose-300',
  },
  {
    label: 'Agribisnis, Peternakan & Perikanan',
    value: 16,
    detail: '237 Data',
    bar: 'bg-emerald-300',
  },
  {
    label: 'Jasa & Layanan',
    value: 13,
    detail: '193 Data',
    bar: 'bg-sky-300',
  },
  {
    label: 'Digital, Teknologi & Kreatif',
    value: 12,
    detail: '178 Data',
    bar: 'bg-brand-blue',
  },
];

export const CATEGORY_BADGE_COLORS: Record<YouthCategory, string> = {
  Kewirausahaan: 'bg-brand-yellow',
  'Kriya & Kreatif': 'bg-brand-purple',
  'Teknologi & Digital': 'bg-brand-blue',
  'Olahraga & Prestasi': 'bg-brand-mint',
  'Sosial & Komunitas': 'bg-brand-peach',
};

export const CATEGORY_ICONS: Record<YouthCategory, string> = {
  Kewirausahaan: '🌱',
  'Kriya & Kreatif': '🎨',
  'Teknologi & Digital': '💻',
  'Olahraga & Prestasi': '🏅',
  'Sosial & Komunitas': '🤝',
};
